### ISSUE TITLE
I would like to reprint your data packs

### ISSUE THREAD

**Issue by Despaitre876** [lanzhi6/BluestarTpsControl#2]
Hello, I would like to reprint your data packs Tectonic v2 to the forum website in China mcbbs.net, I will mount your download link

**Comment by CyanTachyon** [comment]
抱歉,我英语不好。你的意思是想将我的插件打包进你的插件中，然后发布到mcbbs吗？

**Comment by Despaitre876** [comment]
我想把你的数据包Tectonic v2转载到mcbbs

**Comment by CyanTachyon** [comment]
> 我想把你的数据包Tectonic v2转载到mcbbs

额,你是不是找错人了.我完全不知道Tectonic v2是什么
